### ISSUE TITLE
The code doesn't work with the latest release of Fast.ai

### ISSUE THREAD

**Issue by heytitle** [dilpreetsingh/Content-Based-Search#1]
Hi,

Thanks for the nice article.

It seems that Fast.ai has recently released a new API. The new interface is quite significantly different from the previous one. Consequently, `content_based_search.py` is no longer working out of the box. 

I needed to change several things to make it work. If you want, I can create a pull request including the change and a Jupyter notebook.

Cheers,
Pat

**Comment by dilpreetsingh** [comment]
Would be great if you wanted to send through a pull
